### ISSUE TITLE
project scraper reports error

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#147]
```
docker-compose --file docker-compose.yml --file docker-compose.prod.yml exec tasks python app.py --task projects
2018-07-25 13:35:41,579 Scraper [INFO] //www.esciencecenter.nl/project/ewatercycle-ii
Traceback (most recent call last):
  File "app.py", line 55, in <module>
    run_task()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 45, in run_task
    sync_projects()
  File "/app/corporate.py", line 50, in sync_projects
    projects = get_projects()
  File "/app/corporate.py", line 14, in get_projects
    include_deep_info=True)
  File "/app/Scraper.py", line 82, in __init__
    self.get_projects()
  File "/app/Scraper.py", line 98, in get_projects
    r = requests.get(project["url"])
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '//www.esciencecenter.nl/project/ewatercycle-ii': No schema supplied. Perhaps you meant http:////www.esciencecenter.nl/project/ewatercycle-ii?
```

**Comment by Tommos0** [comment]
Fixed in https://github.com/research-software-directory/tasks-nlesc/commit/37eddf8763f1d2a650ef8bff8ff94404a55fdcee
