### ISSUE TITLE
uncaught exception in releases task

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#179]
```
2018-11-29 10:22:49,461 releases [INFO] 42/124 "DateTime input field for Ext JS": 10.0000/FIXME error resolving doi.
2018-11-29 10:22:52,026 releases [INFO] 43/124 "FAIR Data Point": 10.5281/zenodo.1083950 no valid CITATION.cff found in any release.
2018-11-29 10:22:53,754 releases [INFO] 44/124 "FastMLC": 10.5281/zenodo.926819 no valid CITATION.cff found in any release.
Traceback (most recent call last):
  File "app.py", line 62, in <module>
    run_task()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 53, in run_task
    sync_releases(db)
  File "/app/releases.py", line 205, in sync_releases
    scraper = ReleaseScraper(conceptdoi)
  File "/app/releases.py", line 84, in __init__
    self.fetch_zenodo_data_versioned_dois()
  File "/app/releases.py", line 151, in fetch_zenodo_data_versioned_dois
    r.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://zenodo.org/api/records?q=conceptdoi:%2210.5281/zenodo.1045122%22&all_versions=true&size=100
```

I tried the URL a couple minutes afterwards, and it gave me a bunch of results, so it's not a throttling issue like I though at first.

**Comment by jspaaks** [comment]
Havent seen this error in a while, closing.
