### ISSUE TITLE
error with zotero task

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#180]
```
2018-11-29 10:31:22,587 releases [INFO] 117/124 "cffinit": 10.5281/zenodo.1404735 OK
2018-11-29 10:31:22,870 releases [INFO] 118/124 "ESMValTool": 10.17874/ac8548f0315 doi is not a Zenodo doi.
2018-11-29 10:31:25,384 releases [INFO] 119/124 "yatiml": 10.5281/zenodo.1478048 no valid CITATION.cff found in any release.
2018-11-29 10:31:27,222 releases [INFO] 120/124 "JupyterLab dataset browser for THREDDS": 10.5281/zenodo.1241006 OK
2018-11-29 10:31:29,032 releases [INFO] 121/124 "Experiment Launcher": 10.5281/zenodo.1453264 no valid CITATION.cff found in any release.
2018-11-29 10:31:31,099 releases [INFO] 122/124 "Satsense": 10.5281/zenodo.1463015 OK
2018-11-29 10:31:33,741 releases [INFO] 123/124 "cerulean": 10.5281/zenodo.1478077 no valid CITATION.cff found in any release.
2018-11-29 10:31:35,874 releases [INFO] 124/124 "lofar-ld": 10.5281/zenodo.1481766 OK
2018-11-29 10:31:37,955 zotero [INFO] 4 new/updated zotero items
2018-11-29 10:31:40,140 zotero [INFO] Items to save: 3
Traceback (most recent call last):
  File "app.py", line 62, in <module>
    run_task()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 54, in run_task
    zotero_sync()
  File "/app/zotero.py", line 126, in zotero_sync
    raise Exception('error saving zotero items', str(resp.json()))
Exception: ('error saving zotero items', '{\'error\': "\'Blueprint\' object has no attribute \'json_decoder\'", \'class\': \'AttributeError\', \'traceback\': [\'  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request\\n    rv = self.dispatch_request()\\n\', \'  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request\\n    return self.view_functions[rule.endpoint](**req.view_args)\\n\', \'  File "/app/src/permission.py", line 64, in wrapper\\n    return func(*args, **kwargs)\\n\', \'  File "/app/src/json_response.py", line 46, in __call__\\n    data, *status_code = self.f(*args, **kwargs)\\n\', \'  File "/app/src/routes.py", line 146, in _update_or_insert\\n    data = flask.request.get_json(force=True, silent=True)\\n\', \'  File "/usr/local/lib/python3.6/site-packages/flask/wrappers.py", line 150, in get_json\\n    rv = json.loads(data)\\n\', \'  File "/usr/local/lib/python3.6/site-packages/flask/json/__init__.py", line 199, in loads\\n    _load_arg_defaults(kwargs)\\n\', \'  File "/usr/local/lib/python3.6/site-packages/flask/json/__init__.py", line 117, in _load_arg_defaults\\n    bp.json_decoder if bp and bp.json_decoder\\n\']}')

```

**Comment by jspaaks** [comment]
seems related: https://github.com/dpgaspar/Flask-AppBuilder/issues/741
the "blueprint" error is actually generated by ``backend``, which indeed was updated to 0.12.3 recently , which apparently is affected by this error. Should be solved by upgrading to 0.12.4
