### ISSUE TITLE
possible error with harvesting mentions

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#279]
needs looking into
```
rsd-frontend     | [2019-04-11 16:18:27,253] ERROR in app: Exception on / [GET]
rsd-frontend     | Traceback (most recent call last):
rsd-frontend     |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
rsd-frontend     |     response = self.full_dispatch_request()
rsd-frontend     |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
rsd-frontend     |     rv = self.handle_user_exception(e)
rsd-frontend     |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
rsd-frontend     |     reraise(exc_type, exc_value, tb)
rsd-frontend     |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
rsd-frontend     |     raise value
rsd-frontend     |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rsd-frontend     |     rv = self.dispatch_request()
rsd-frontend     |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
rsd-frontend     |     return self.view_functions[rule.endpoint](**req.view_args)
rsd-frontend     |   File "/src/app/application.py", line 94, in index
rsd-frontend     |     mentions=get_mentions(all_software),
rsd-frontend     |   File "/src/app/application.py", line 65, in get_mentions
rsd-frontend     |     if False in [required in mention['foreignKey'].keys() for required in requireds]: continue
rsd-frontend     |   File "/src/app/application.py", line 65, in <listcomp>
rsd-frontend     |     if False in [required in mention['foreignKey'].keys() for required in requireds]: continue
rsd-frontend     | AttributeError: 'NoneType' object has no attribute 'keys'

```

this was on localhost, maybe there was something different with the mentions data there. I think this is the data version https://github.com/research-software-directory/research-software-directory/tree/90df62f7dd2693e0e64dc8c96d39cabcb9d3a875 not sure

**Comment by jspaaks** [comment]
can't reproduce. closing for now
