### ISSUE TITLE
harvest citations error: TOO MANY REQUESTS zenodo.org/api

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/research-software-directory#302]
Happened while testing the https://github.com/research-software-directory/research-software-directory/pull/297 PR.

Started from scratch and after all Docker container where up I tried to harvest the citations with:

```sh
docker-compose --project-name rsd exec harvesting python app.py harvest citations 
2019-10-17 15:22:17,543 releases [ERROR] 1/90: 10.0000/FIXME error resolving doi.
...
2019-10-17 15:22:42,420 releases [ERROR] 15/90: 10.5281/zenodo.1045198 no valid CITATION.cff found in any release.
Traceback (most recent call last):
  File "app.py", line 110, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 77, in harvest_citations
    get_citations(db, dois)
  File "/app/releases.py", line 217, in get_citations
    release = ReleaseScraper(doi)
  File "/app/releases.py", line 83, in __init__
    self.fetch_zenodo_data_conceptdoi()
  File "/app/releases.py", line 148, in fetch_zenodo_data_conceptdoi
    r.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: TOO MANY REQUESTS for url: https://zenodo.org/api/records/1045249
```

**Comment by jspaaks** [comment]
Documentation suggests a rate limit of 5000 requests/hour https://about.zenodo.org/principles/ (I assume this is for authenticated use)

https://about.zenodo.org/principles/

PR #308 may resolve the situation.
