### ISSUE TITLE
ssl error when harvesting project descriptions

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/research-software-directory#309]
when I do 
```
docker-compose exec harvesting python app.py harvest projects
```
I get a 

```
rsd-harvesting   | Traceback (most recent call last):
rsd-harvesting   |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
rsd-harvesting   |     chunked=chunked)
rsd-harvesting   |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
rsd-harvesting   |     self._validate_conn(conn)
rsd-harvesting   |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
rsd-harvesting   |     conn.connect()
rsd-harvesting   |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
rsd-harvesting   |     ssl_context=context)
rsd-harvesting   |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 345, in ssl_wrap_socket
rsd-harvesting   |     return context.wrap_socket(sock, server_hostname=server_hostname)
rsd-harvesting   |   File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
rsd-harvesting   |     _context=self, _session=session)
rsd-harvesting   |   File "/usr/local/lib/python3.6/ssl.py", line 817, in __init__
rsd-harvesting   |     self.do_handshake()
rsd-harvesting   |   File "/usr/local/lib/python3.6/ssl.py", line 1077, in do_handshake
rsd-harvesting   |     self._sslobj.do_handshake()
rsd-harvesting   |   File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
rsd-harvesting   |     self._sslobj.do_handshake()
rsd-harvesting   | ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
```

Seems like we need to do something with certificates https://requests.readthedocs.io/en/master/user/advanced/#ssl-cert-verification. 

Or simpler option, add ``verify=False`` when making the request

**Comment by jspaaks** [comment]
(after some discussion with @sverhoeven) this may be related to our certificate authority having split off from its parent a little while ago. Now when ``requests`` checks against a list of known certificate authorities, it could be that ours is not on it and it throws an error.

BTW the Alpine we're running is already the newest (3.10.3) according to https://www.alpinelinux.org/
```
$ docker-compose exec harvesting  /bin/sh
# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.10.3
PRETTY_NAME="Alpine Linux v3.10"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

I also tried updating ``requests`` to its latest version 2.22.0, didn't work.

**Comment by sverhoeven** [comment]
Added intermediate cert to https://www.esciencecenter.nl/, now besides web browsers also curl and Python don't complain anymore.
