### ISSUE TITLE
Thesis not found in mentions

### ISSUE THREAD

**Issue by arnikz** [research-software-directory/research-software-directory#311]
I've added a thesis to Zotero (`12/11/2019, 14:39:34`) and linked it to the software but I don't see it back in the RSD admin page. Did I miss a step?

**Comment by Tommos0** [comment]
Hi, what did you add? I see one item from yesterday in zotero, is that the one?

```
@misc{lindhout_software_2019,
	title = {Software in de etalage},
	url = {https://www.riannelindhout.nl/software-in-de-etalage/},
	language = {Dutch},
	author = {Lindhout, Rianne},
	month = dec,
	year = {2019}
}
```

**Comment by jspaaks** [comment]
Nope that was me

**Comment by jspaaks** [comment]
I think there are problems with the harvesting, which have been solved in bleeding edge but not production.

**Comment by arnikz** [comment]
@Tommos0: did you find the entry? My username + date should be enough (unique) to find it;-)

**Comment by jspaaks** [comment]
Just for your information: linking software and the thesis record does not happen through the 'Related' tab in Zotero, instead it happens through the Research Software Directory's admin interface. See: https://github.com/research-software-directory/research-software-directory/blob/master/docs/instruction/README.md

**Comment by Tommos0** [comment]
No, haven't found it. Zotero doesn't show creator usernames

**Comment by jspaaks** [comment]
I'm guessing this is the record that Arnold is talking about https://www.zotero.org/groups/1689348/netherlands_escience_center/items/itemKey/63X34MNP/

**Comment by jspaaks** [comment]
I just built ``master`` and ``harvest``ed all resources, then ``resolve``d. The record above is displayed correctly, so it is indeed a problem with the harvesting in production v bleeding edge.

**Comment by arnikz** [comment]
> Just for your information: linking software and the thesis record does not happen through the 'Related' tab in Zotero, instead it happens through the Research Software Directory's admin interface. See: https://github.com/research-software-directory/research-software-directory/blob/master/docs/instruction/README.md

All right, however, it doesn't even show up in the _Mentions_ of the RSD admin page.

**Comment by Tommos0** [comment]
Seems the Zotero sync is indeed broken with the current version:

```
/app # python app.py harvest mentions
2019-12-13 09:20:49,330 zotero [INFO] Database collection 'mention' is currently at version 5590; Zotero library 1689348 is currently at version 5655.
2019-12-13 09:20:50,484 zotero [INFO] Found 25 new or updated items in Zotero library 1689348 since version 5590.
2019-12-13 09:20:52,964 zotero [WARNING] S2VTBC48 does not have a title
2019-12-13 09:20:52,964 zotero [WARNING] 'Solution of the large matrix equations which occur in response theory' is not part of a project (key = 8AMKYLCL)
2019-12-13 09:20:52,965 zotero [WARNING] 'The iterative calculation of a few of the lowest eigenvalues and corresponding eigenvectors of large real-symmetric matrices' is not part of a project (key = 8QZGD3DA)
2019-12-13 09:20:52,966 zotero [WARNING] 'Actin Networks Voltage Circuits' is not part of a project (key = 8BLMYB3G)
2019-12-13 09:20:52,966 zotero [WARNING] 'Actin droplet machine' is not part of a project (key = MB9CELTM)
2019-12-13 09:20:52,967 zotero [INFO] https://blog.esciencecenter.nl/why-all-youll-ever-need-is-markdown-dc604f0ab309 = eScience Blog
2019-12-13 09:20:54,619 zotero [INFO] https://blog.esciencecenter.nl/narcis-connects-to-the-research-software-directory-320c82ddbf2f = eScience Blog
2019-12-13 09:20:55,812 zotero [INFO] https://blog.esciencecenter.nl/entangled-1744448f4b9f = eScience Blog
2019-12-13 09:20:57,089 zotero [WARNING] 'GGIR: A Research Community–Driven Open Source R Package for Generating Physical Activity and Sleep Outcomes From Multi-Day Raw Accelerometer Data' is not part of a project (key = C3JIM5IW)
2019-12-13 09:20:57,090 zotero [WARNING] 'Analyzing Protein Interaction Networks Using Structural Information' is not part of a project (key = QCNTLJ6D)
2019-12-13 09:20:57,091 zotero [INFO] Items to save: 18
Traceback (most recent call last):
  File "app.py", line 110, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 60, in harvest_mentions
    get_mentions(since_version=since_version, keys=keys)
  File "/app/zotero.py", line 146, in get_mentions
    raise Exception('error saving zotero items', str(resp.json()))
Exception: ('error saving zotero items', '{\'error\': "None is not of type \'string\'", \'class\': \'ValidationError\', \'path\': [\'author\']}')
```

**Comment by jspaaks** [comment]
Hi @arnikz, looks like this issue has been resolved, correct?

**Comment by arnikz** [comment]
Yes, thanks.
