### ISSUE TITLE
Ratelimit code releases throws typeerror

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/research-software-directory#434]
While running `docker-compose exec harvesting python app.py harvest all` I got a TypeError.

Log:
```
2020-10-05 09:03:11,192 releases [INFO] 42/119 "10.5281/zenodo.1220113" (Kernel Tuner): OK
Traceback (most recent call last):
  File "app.py", line 140, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 104, in harvest_all
    get_citations(db, dois)
  File "/app/releases.py", line 235, in get_citations
    release = ReleaseScraper(software["conceptDOI"])
  File "/app/releases.py", line 90, in __init__
    self.fetch_zenodo_data_versioned_dois()
  File "/app/releases.py", line 166, in fetch_zenodo_data_versioned_dois
    if int(r.headers.get('x-ratelimit-remaining')) < 10:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

<details><summary>Pip list</summary>

```
docker-compose exec harvesting pip3 list
Package         Version   
--------------- ----------
beautifulsoup4  4.6.0     
bibtexparser    1.1.0     
certifi         2020.4.5.1
cffconvert      1.3.3     
chardet         3.0.4     
click           6.7       
dateutils       0.6.6     
docopt          0.6.2     
feedparser      5.2.1     
future          0.18.2    
idna            2.7       
pathlib         1.0.1     
pip             19.1.1    
PyJWT           1.5.3     
pykwalify       1.7.0     
pymongo         3.6.1     
pyparsing       2.4.7     
python-dateutil 2.6.1     
pytz            2019.3    
PyYAML          5.3.1     
Pyzotero        1.3.1     
requests        2.20.0    
ruamel.yaml     0.15.100  
setuptools      41.0.1    
six             1.14.0    
urllib3         1.24.3    
wheel           0.33.3  
```
</details>

**Comment by jspaaks** [comment]
I just rediscovered a rate limiting decorator in util.py, might be worth a try.

https://github.com/research-software-directory/research-software-directory/blob/00fdaf10814372f385aa5ab4f276fb72db4cb339/harvesting/util.py#L13-L45

**Comment by eriktks** [comment]
I had the same issue as Stefan for the file releases.py and also for the file oaipmh.py.

 Log:

> 2020-10-07 10:25:38,934 oaipmh [INFO]  72/119: retrieved datacite4 metadata for 10.5281/zenodo.3252665
Traceback (most recent call last):
  File "app.py", line 140, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 107, in harvest_all
    list_records(dois)
  File "/app/oaipmh.py", line 113, in list_records
    record_elem = get_datacite()
  File "/app/oaipmh.py", line 62, in get_datacite
    if int(response.headers.get('x-ratelimit-remaining')) < 10:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
