### ISSUE TITLE
Error when harvesting

### ISSUE THREAD

**Issue by cwmeijer** [research-software-directory/research-software-directory#438]
When running the 'harvest all' command from the readme, I get the following error:

```
2020-10-06 09:19:24,163 Scraper [INFO] 141/147: Processing https://www.esciencecenter.nl/projects/perfect-fit/
2020-10-06 09:19:26,288 Scraper [INFO] 142/147: Processing https://www.esciencecenter.nl/projects/is-enes3/
2020-10-06 09:19:28,510 Scraper [INFO] 143/147: Processing https://www.esciencecenter.nl/projects/strap/
2020-10-06 09:19:30,817 Scraper [INFO] 144/147: Processing https://www.esciencecenter.nl/projects/mydigitwin/
2020-10-06 09:19:32,501 Scraper [INFO] 145/147: Processing https://www.esciencecenter.nl/projects/carrier/
2020-10-06 09:19:34,267 Scraper [INFO] 146/147: Processing https://www.esciencecenter.nl/projects/cheops/
2020-10-06 09:19:35,188 Scraper [INFO] 147/147: Processing https://www.esciencecenter.nl/projects/scaling-up-pan-genomics-for-plant-breeding/
2020-10-06 09:19:36,635 oaipmh [INFO] Still need to enrich and correct the metadata. Currectly serving Zenodo's metadata as-is.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/xml/etree/ElementTree.py", line 789, in _get_writer
    write = file_or_filename.write
AttributeError: 'str' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 140, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 107, in harvest_all
    list_records(dois)
  File "/app/oaipmh.py", line 145, in list_records
    method='xml')
  File "/usr/local/lib/python3.6/xml/etree/ElementTree.py", line 759, in write
    with _get_writer(file_or_filename, enc_lower) as write:
  File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/xml/etree/ElementTree.py", line 796, in _get_writer
    errors="xmlcharrefreplace")
FileNotFoundError: [Errno 2] No such file or directory: '/app/oaipmh-cache/datacite4/listrecords.xml'
```

I don't know yet if it did what it was supposed to do.

After, the automatic 'resolve all' harvesting task seems to work. It gives only green output like:
```
...
rsd-harvesting   | 2020-10-06 09:25:01,262 cache [INFO] processing project https://www.esciencecenter.nl/projects/darkgenerators/
rsd-harvesting   | 2020-10-06 09:25:01,263 cache [INFO] processing project https://www.esciencecenter.nl/projects/reaxpro-h2020/
rsd-harvesting   | 2020-10-06 09:25:01,264 cache [INFO] processing project https://www.esciencecenter.nl/projects/cortex/
rsd-harvesting   | 2020-10-06 09:25:01,266 cache [INFO] processing project https://www.esciencecenter.nl/projects/esiwace2-2/
rsd-harvesting   | 2020-10-06 09:25:01,268 cache [INFO] processing project https://www.esciencecenter.nl/projects/perfect-fit/
rsd-harvesting   | 2020-10-06 09:25:01,270 cache [INFO] processing project https://www.esciencecenter.nl/projects/is-enes3/
rsd-harvesting   | 2020-10-06 09:25:01,271 cache [INFO] processing project https://www.esciencecenter.nl/projects/strap/
rsd-harvesting   | 2020-10-06 09:25:01,272 cache [INFO] processing project https://www.esciencecenter.nl/projects/mydigitwin/
rsd-harvesting   | 2020-10-06 09:25:01,274 cache [INFO] processing project https://www.esciencecenter.nl/projects/carrier/
rsd-harvesting   | 2020-10-06 09:25:01,275 cache [INFO] processing project https://www.esciencecenter.nl/projects/cheops/
rsd-harvesting   | 2020-10-06 09:25:01,277 cache [INFO] processing project https://www.esciencecenter.nl/projects/scaling-up-pan-genomics-for-plant-breeding/
...
```
That looks good to me. However, I don't see any projects or persons in the interface. This would indicate that the harvesting is not working, but this might be another problem. As I understood from Faruk, even without the harvesting job, the RSD is supposed to be filled some data already, which I'm not seeing.

Anyway, this issue is about the error in the output during 'harvest all'.

**Comment by jspaaks** [comment]
Judging by "/app/oaipmh-cache/datacite4/listrecords.xml", the problem is that the code expects a volume / directory to be present, and it isn't

Two things to check:

1. do you have anything under ./docker-volumes/
1. in harvesting container, is there an /app/oaipmh-cache directory

The sample data is loaded from `database/db-init` before any harvesting gets done. You can check the container's logs by 
```shell
docker-compose logs database
```
It will say something like: `building a list of collections to restore from /db-init dir`

**Comment by cwmeijer** [comment]
The only thing I find about db-init is:
```
Step 1/3 : FROM mongo:3.6
 ---> 099e85880d4e
Step 2/3 : COPY ./db-init /db-init
 ---> Using cache
 ---> d3e8f8c3a7bd
```
While starting 'docker up'.

Also, when I use the API all data seems to be present, as it's nicely returning data for all the 147 projects on 'https://localhost/api/project'.

**Comment by jspaaks** [comment]
Maybe a typo, but just in case. The commands are `docker-compose` based, not `docker` based
```
docker-compose build
source rsd-secrets.env
docker-compose up -d
```

Also, the text `Step 1/3` etc is feedback from one of the build steps, whereas the lines I was referring to come from a running container (i.e. as a result of the `docker-compose up` step)

if you want to follow the docker compose logs as they stream, add the --follow flag to the command:
```
docker-compose logs database --follow # for logs from the database service
docker-compose logs --follow          # for logging from anywhere
```

**Comment by cwmeijer** [comment]
Indeed, 'docker-compose up'.
And when I was referring to 'actual logs', I meant those that you get using 'docker-compose logs'. I can see that was a bit unclear.

**Comment by jspaaks** [comment]
From the error message, the error comes from here:
https://github.com/research-software-directory/research-software-directory/blob/00fdaf10814372f385aa5ab4f276fb72db4cb339/harvesting/oaipmh.py#L142-L145

This code is triggered when you do a 
```
docker-compose exec harvesting harvest all
```

but more specifically, when you do 

```
docker-compose exec harvesting harvest metadata
```
(might speed up debugging)

Check the main README to see if the oai-pmh files can be served or not ([here](https://github.com/research-software-directory/research-software-directory#oai-pmh)).

Also, you may still get a 429 error (making too many requests in a short amount of time), see https://github.com/research-software-directory/research-software-directory/issues/434

**Comment by cwmeijer** [comment]
Checked both directories:
1. ./docker-volumes/
1. /app/oaipmh-cache/

Both exist but are empty.


The suggested 
```
docker-compose exec harvesting harvest metadata
```
Should be 
```
docker-compose exec harvesting python app.py harvest metadata
```
Which indeed is a lot quicker for debugging.

**Comment by jspaaks** [comment]
You're right, I erroneously left out part of the command.

**Comment by cwmeijer** [comment]
Checked aoi-pmh service but when verifying the service through
```
http://localhost/oai-pmh?verb=ListRecords&metadataPrefix=datacite4
```
I get 502 Bad gateway. In the logs:
```
rsd-database     | 2020-10-07T13:00:09.730+0000 I NETWORK  [conn12] end connection 172.19.0.8:34116 (3 connections now open)
rsd-nginx-ssl    | 2020/10/07 13:00:17 [error] 15#15: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /oai-pmh?verb=ListRecords&metadataPrefix=datacite4 HTTP/1.1", upstream: "http://172.19.0.2:80/oai-pmh?verb=ListRecords&metadataPrefix=datacite4", host: "localhost"
rsd-nginx-ssl    | 172.19.0.1 - - [07/Oct/2020:13:00:17 +0000] "GET /oai-pmh?verb=ListRecords&metadataPrefix=datacite4 HTTP/1.1" 502 150 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0" "-"
rsd-nginx-ssl    | 2020/10/07 13:00:17 [error] 15#15: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.19.0.2:80/favicon.ico", host: "localhost", referrer: "https://localhost/oai-pmh?verb=ListRecords&metadataPrefix=datacite4"
rsd-nginx-ssl    | 172.19.0.1 - - [07/Oct/2020:13:00:17 +0000] "GET /favicon.ico HTTP/1.1" 502 150 "https://localhost/oai-pmh?verb=ListRecords&metadataPrefix=datacite4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0" "-"
```

It seems to me that the only code in the repo that refers to the missing file is in oaipmh.py, list_records, line 142. That seems to be a service for metadata harvesting (had to google the acronym of course).

The missing dir should be created in line 72. While trying to run and debug, I'm now only getting 502 status codes, so I'm kinda blocked by that at the moment. I'm suspecting the whole 502 thing is not really related to the error I was trying to solve about the missing cache file.
