### ISSUE TITLE
pyzotero.zotero_errors.ResourceNotFound

### ISSUE THREAD

**Issue by AdamBelloum** [research-software-directory/research-software-directory#469]
I have some issues with Zotero. the URL seems to be corrupted, in the rds-secrets.env ZOTERO_LIBRARY is set to full URL: https://www.zotero.org/groups/2578219/1234group/ 
 

- MAC OS Darwin
- Which version of the software you're running
- Error message

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pyzotero/zotero.py", line 431, in _retrieve_data
    self.request.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.zotero.org/groups/https%3A//www.zotero.org/groups/2578219/1234group/items?format=json&limit=100

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 132, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 98, in harvest_all
    get_mentions(since_version=None)
  File "/app/zotero.py", line 79, in get_mentions
    their_last_version = client.last_modified_version()
  File "/usr/local/lib/python3.6/site-packages/pyzotero/zotero.py", line 683, in last_modified_version
    self.items(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/pyzotero/zotero.py", line 198, in wrapped_f
    retrieved = self._retrieve_data(func(self, *args))
  File "/usr/local/lib/python3.6/site-packages/pyzotero/zotero.py", line 433, in _retrieve_data
    error_handler(self, self.request)
  File "/usr/local/lib/python3.6/site-packages/pyzotero/zotero.py", line 1643, in error_handler
    raise error_codes.get(req.status_code)(err_msg(req))
pyzotero.zotero_errors.ResourceNotFound: 
Code: 404
URL: https://api.zotero.org/groups/https%3A//www.zotero.org/groups/2578219/1234group/items?format=json&limit=100
Method: GET
Response: <h1>Not Found</h1>

**Comment by jspaaks** [comment]
Hi Adam,
thanks for the report. Can you verify that in `rsd-secrets.env`, your `ZOTERO_LIBRARY` is set to `2578219`, not https://www.zotero.org/groups/2578219/1234group/? See https://github.com/research-software-directory/research-software-directory#zotero_library

**Comment by AdamBelloum** [comment]
ZOTERO_LIBRARY=2578219  gives the same error

**Comment by jspaaks** [comment]
> ZOTERO_LIBRARY=2578219 gives the same error

In the terminal where you do `docker-compose exec harvesting python app.py harvest mentions`, did you `source` your `rsd-secrets.env` after you changed the value for `ZOTERO_LIBRARY`?

**Comment by AdamBelloum** [comment]
works thanks

**Comment by jspaaks** [comment]
Closing
